import mongoose from "mongoose";

const CustomerAccountSchema = new mongoose.Schema(
  {
    accountType: { type: String, required: true },
    accountCode: { type: String, default: "", unique: true },
    name: { type: String, default: "" },
    addressLine1: { type: String, default: "" },
    addressLine2: { type: String, default: "" },
    city: { type: String, default: "" },
    state: { type: String, default: "" },
    country: { type: String, default: "" },
    pinCode: { type: String, default: "" },
    contactPerson: { type: String, default: "" },
    email: { type: String, default: "" },
    telNo: { type: String, default: "" },
    panNo: { type: String, default: "" },
    gstNo: { type: String, default: "" },
    kycNo: { type: String, default: "" },
    branch: { type: String, default: "" },
    hub: { type: String, default: "" },
    companyName: { type: String, default: "" },
    salesPersonName: { type: String, default: "" },
    referenceBy: { type: String, default: "" },
    managedBy: { type: String, default: "" },
    collectionBy: { type: String, default: "" },
    accountManager: { type: String, default: "" },
    reportPerson: { type: String, default: "" },
    salesCoordinator: { type: String, default: "" },
    applicableTariff: { type: String, default: "" },
    gst: { type: String, default: "" },
    account: { type: String, default: "Activate" },
    fuel: { type: String, default: "" },
    rateModify: { type: String, default: "" },
    billingEmailId: { type: String, default: "" },
    paymentTerms: { type: String, default: "" },
    rateType: { type: String, default: "" },
    parentCode: { type: String, default: "" },
    billingTag: { type: String, default: "" },
    currency: { type: String, default: "" },
    csb: { type: String, default: "" },
    branded: { type: String, default: "" },
    handling: { type: String, default: "" },
    modeType: { type: String, default: "" },
    deactivateReason: { type: String, default: "" },
    enableOS: { type: Boolean, default: false },
    openingBalance: { type: String, default: "" },
    creditLimit: { type: String, default: "" },
    leftOverBalance: { type: Number, default: 0 },
    noOfDaysCredit: { type: String, default: "" },
    portalBalance: { type: String, default: "" },
    volumeMetricWtSector: { type: String, default: "" },
    volumeMetricWtService: { type: String, default: "" },
    divisible: { type: String, default: "" },
    volWtDivisibleTable: { type: Array, default: [] },
    allServiceSettings: { type: Boolean, default: false },
    serviceSettingsSector: { type: String, default: "" },
    serviceSettingsService: { type: String, default: "" },
    serviceSettingVolDiscTable: { type: Array, default: [] },
    enableVolDiscount: { type: Boolean, default: false },
    volDiscountSector: { type: String, default: "" },
    volDiscountService: { type: String, default: "" },
    volDiscountWeight: { type: String, default: "" },
    volDiscount: { type: String, default: "" },
    enablePortalPassword: { type: Boolean, default: false },
    portalPasswordSector: { type: String, default: "" },
    upsLabel: { type: Boolean, default: false },
    yadelLabel: { type: Boolean, default: false },
    post11Label: { type: Boolean, default: false },
    dhlLabel: { type: Boolean, default: false },
    upsStandardLabel: { type: Boolean, default: false },
    enableLabelSetting: { type: Boolean, default: false },
    rateHikeService: { type: String, default: "" },
    rateHikeAmount: { type: String, default: "" },
    rateHikeFrom: { type: String, default: "" },
    rateHikeTo: { type: String, default: "" },
    rateHikeTable: { type: Array, default: [] },
    signatureImage: { type: String, default: "" },
    stampImage: { type: String, default: "" },
    bankName: { type: String, default: "" },
    accountNumber: { type: String, default: "" },
    companyCode: { type: String, default: "" },
    ifsc: { type: String, default: "" },
    bankAddress: { type: String, default: "" },
    gm: { type: String, default: "" },
    rm: { type: String, default: "" },
    sm: { type: String, default: "" },
    se: { type: String, default: "" },
  },
  { timestamps: true }
);

// Create model
export default mongoose.models.CustomerAccount ||
  mongoose.model("CustomerAccount", CustomerAccountSchema);
